name: Deploy to Cloudflare Workers

on:
  push:
    branches:
      - master
    paths-ignore:
      - '**.md'
  repository_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    name: Build & Deploy
    steps:
      - uses: actions/checkout@v4
      - name: Generate wrangler.toml
        run: |
          rm -f wrangler.toml
          export CUSTOM_DOMAIN="${{ secrets.CUSTOM_DOMAIN || 'libcuda.so' }}"
          envsubst < wrangler.template.toml > wrangler.toml
          cat wrangler.toml
      - name: Publish
        uses: cloudflare/wrangler-action@v3
        env:
          CUSTOM_DOMAIN: ${{ secrets.CUSTOM_DOMAIN || 'libcuda.so' }}
        with:
          apiToken: ${{ secrets.CF_API_TOKEN }}
          accountId: ${{secrets.CF_ACCOUNT_ID}}
          vars:
            CUSTOM_DOMAIN
          command: deploy --env production --minify src/index.js
          environment: production
